# Generated by Django 4.1.1 on 2022-11-12 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_forget'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Forget',
        ),
    ]
